<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <Description>A Plugin that allows the creation of Polls within a Text-Channel!</Description>
    <PackageProjectUrl>https://github.com/Hitamaru16/ChatPoll</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
